# Generated by Django 4.0.2 on 2022-03-03 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(max_length=60)),
                ('category', models.ManyToManyField(blank=True, null=True, to='auctions.Category')),
            ],
        ),
    ]
